#!/bin/sh
# Start nghttpx HTTP/2 proxy with ability to set backend and extra
# runtime args

args=""
if test -n "$HOST"; then
    if test -z "$PORT"; then
       PORT=80
    fi
    args="$args --backend $HOST,$PORT"
fi
if test -n "$ARGS"; then
    args="$args $ARGS"
fi

mkdir -p /data/etc /data/etc/ssl/certs /data/etc/ssl/private /data/logs /data/run

if ! -r /data/etc/nghttpx.conf; then
  cp /etc/nghttpx.conf /data/etc/nghttpx.conf
fi

exec /usr/bin/nghttpx --frontend-no-tls --conf /data/etc/nghttpx.conf $args
